/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOG_RPC_H_RPCGEN
#define _LOG_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct arg {
	char *user;
	char *operacion;
	char *datetime;
};
typedef struct arg arg;

#define LOGRPC 0x20000001
#define LOGRPC_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOG_OPERATION 1
extern  void * log_operation_1(arg *, CLIENT *);
extern  void * log_operation_1_svc(arg *, struct svc_req *);
extern int logrpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOG_OPERATION 1
extern  void * log_operation_1();
extern  void * log_operation_1_svc();
extern int logrpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arg (XDR *, arg*);

#else /* K&R C */
extern bool_t xdr_arg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOG_RPC_H_RPCGEN */
