/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "log_rpc.h"

bool_t
xdr_arg (XDR *xdrs, arg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operacion, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->datetime, 256))
		 return FALSE;
	return TRUE;
}
